sites:
  # 新增：用于对照测试的稳定网站
  - name: Google Test
    url: https://www.google.com
    expectedStatusCodes: [200] # 期望返回200状态码

  # 你的原有服务
  - name: 湛青数科网盘
    url: https://drive.zydt.saop.cc/
    expectedStatusCodes: [200]

  - name: 湛江青年数字科技协会官网
    url: https://zydt.saop.cc/
    expectedStatusCodes: [200]
