# 基本信息 - 必须配置
owner: Maple2085
repo: my-zydt-status

# 监控站点列表
sites:
  - name: 湛青数科网盘
    url: https://drive.zydt.saop.cc/
    expectedStatusCodes: [200] # 期望的HTTP状态码

  - name: 湛江青年数字科技协会官网
    url: https://zydt.saop.cc/
    expectedStatusCodes: [200]

# 状态页面设置
status-website:
  name: 湛青数科服务状态监控 # 页面标题
  baseUrl: /
  logoUrl: https://drive.zydt.saop.cc/d/logo.avif # 从你们网盘加载LOGO
  theme: light # 主题风格 (light 或 dark)
  # cname: status.your-domain.com # 如需自定义域名，取消注释并修改
