owner: Maple2085        # 你的 GitHub 用户名
repo: my-zydt-status    # 仓库名
sites:
  - name: Google
    url: https://google.com
  - name: ZYDT Main
    url: https://zydt.saop.cc
  - name: ZYDT Drive
    url: https://drive.zydt.saop.cc
